### ISSUE TITLE
cordova-plugin-volumen-control cannot build for ios

### ISSUE THREAD

**Issue by faytom** [mgcrea/cordova-plugin-volume-control#4]
I am running cordova 6.0 on my mac. It failed and returned the following error:
Undefined symbols for architecture i386:
  "_DLog", referenced from:
      -[VolumeControl toggleMute:] in VolumeControl.o
      -[VolumeControl isMuted:] in VolumeControl.o
      -[VolumeControl setVolume:] in VolumeControl.o
      -[VolumeControl getVolume:] in VolumeControl.o
      -[VolumeControl getCategory:] in VolumeControl.o
      -[VolumeControl hideVolume:] in VolumeControl.o
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Please help thx in advance!

**Comment by vin-ni** [comment]
+1

**Comment by faytom** [comment]
@vin-ni
locate plugins/cordova-volume-control/src/ios/VolumeControl.m
comment the follow lines which cause the error:
NSLog(@"toggleMute");
NSLog(@"isMuted");
NSLog(@"setVolume: [%f]", volume);
NSLog(@"getVolume");
NSLog(@"getCategory");
NSLog(@"hideVolume");
after that try to rebuild your project, it should resolve your problem.
